name: RNV Dienstplan Sync

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run script
        env:
          RNV_USER: ${{ secrets.RNV_USER }}
          RNV_PASS: ${{ secrets.RNV_PASS }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python monitor.py
