name: RNV Dienstplan Sync

on:
  schedule:
    # Führt das Skript alle 15 Minuten aus
    - cron: '*/15 * * * *'
  workflow_dispatch: # Ermöglicht manuellen Start zum Testen

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
          # pytz brauchen wir nicht, wenn wir die einfache Zeitprüfung oben nutzen

      - name: Run script
        env:
          RNV_USER: ${{ secrets.RNV_USER }}
          RNV_PASS: ${{ secrets.RNV_PASS }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python monitor.py
