name: RNV Dienstplan Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Läuft stündlich

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run monitor
        env:
          RNV_USER: ${{ secrets.RNV_USER }}
          RNV_PASS: ${{ secrets.RNV_PASS }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python monitor.py

     - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Prüfen, ob die Datei existiert
          if [ -f "checkpoint.json" ]; then
            git add checkpoint.json
            # Prüfen, ob sich etwas geändert hat, sonst nichts tun
            if ! git diff --quiet --cached; then
              git commit -m "Update RNV Dienstplan"
              git push
            else
              echo "Keine Änderungen zum Committen."
            fi
          else
            echo "checkpoint.json existiert noch nicht, kein Commit nötig."
          fi
