name: Test ntfy Push

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send test notification
        run: |
          curl -X POST \
            -H "Title: Perdis" \
            -H "X-Icon: https://httpbin.org/image/png" \
            -H "X-Tags: test,github" \
            -H "Priority: 5"
            --data "Test Push funktioniert 🚀 (GitHub Actions)" \
            https://ntfy.sh/mein-rnv-monitor
