name: Test ntfy Push

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send test notification
        run: |
          curl -H "Title: Perdis" \
               -H "Icon: https://fahrerauskunft.rnv-online.de/WebComm/images/icons/ios80x80.png" \
               -d "Test Push funktioniert 🚀" \
               https://ntfy.sh/mein-rnv-monitor
